development:
  adapter: sqlite3
  database: db/development.sqlite
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: mission
  username: username
  password: password
  host: localhost